### ISSUE TITLE
`TypeError: this.socket.end is not a function` when browser is refreshed

### ISSUE THREAD

**Issue by marcusegues** [xmpp-ftw/xmpp-ftw#176]
I am able to open a socket.io connection to the XMPP-FTW server and login to my XMPP server. However, if I refresh the browser, the server crashes:

```
/Users/myProject/node_modules/xmpp-ftw/lib/xmpp.js:104
    if (this.socket) this.socket.end()

TypeError: this.socket.end is not a function
    at Xmpp.logout (/Users/myProject/node_modules/xmpp-ftw/lib/xmpp.js:104:34)
    at Socket.<anonymous> (/Users/myProject/node_modules/xmpp-ftw/lib/xmpp.js:80:14)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:191:7)
    at Socket.emit (/Users/myProject/node_modules/socket.io/lib/socket.js:141:10)
    at Socket.onclose (/Users/myProject/node_modules/socket.io/lib/socket.js:441:8)
    at Client.onclose (/Users/myProject/node_modules/socket.io/lib/client.js:235:24)
    at emitTwo (events.js:111:20)
    at Socket.emit (events.js:194:7)
    at Socket.onClose (/Users/myProject/node_modules/engine.io/lib/socket.js:311:10)
```

Does this have to do with the usage of socket.io?

Using the following XMPP-FTW node.js server:

```const app = require('express'),
  server = require('http').Server(app),
  io = require('socket.io')(server),
  Xmpp = require('xmpp-ftw'),
  Disco = require('xmpp-ftw-disco'),
  Muc = require('xmpp-ftw-muc');

server.listen(5000, function() {
  console.log('XMPP-FTW listening on port %d', server.address().port);
});

io.sockets.on('connection', socket => {
  console.log(
    `A client just connected on ${socket.id}, there are ${io.engine
      .clientsCount} clients.`
  );
  const xmppFtw = new Xmpp.Xmpp(socket);
  xmppFtw.clearListeners();
  xmppFtw.addListener(new Disco());
  xmppFtw.addListener(new Muc());
  socket.xmppFtw = xmppFtw;

  socket.on('disconnect', () => {
    console.log(
      `A client just disconnected, there are ${io.engine.clientsCount} clients.`
    );
    socket.xmppFtw.logout();
  });
});
```

And connecting from a web browser as follows:
``` import SocketIOClient from 'socket.io-client';

const createXmppFtwSocket = () => {
  const socket = SocketIOClient('http://localhost:5000', {
    transports: ['websocket'],
  });
  return Promise.resolve(socket);
};

createXmppFtwSocket().then(socket => {
     socket.on('connect', () => {
      console.log('Connected to XMPP-FTW server.');
    });

    socket.on('xmpp.connection', data => {
      console.log('Connected as', data.jid);
    });

    const options = {
      jid: `me@my.xmpp.server`,
      password: 'password',
      host: 'my.xmpp.server',
    };

    this.xmppFtwSocket.emit('xmpp.login', options);
})
```

**Comment by marcusegues** [comment]
To fix this I can use
```
io.sockets.on('connection', socket => {
  (...)
   socket.end = () => {
     socket.disconnect();
  };
(...)
}
```

But this seems like a hacky way to solve this.

**Comment by marcusegues** [comment]
However, now the error I get on some refreshes is:
```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:582:26)
```

**Comment by lloydwatkin** [comment]
This is because you are using socket.io directly rather than via primus so the API will be a little different. Therefore your patching of socket.io is probably the best way to go for now, unless you switch to primus.
